// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: modules/proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN   MessageType = 0
	MessageType_HELLO     MessageType = 1
	MessageType_QUERY     MessageType = 2
	MessageType_RESULT    MessageType = 3
	MessageType_ERROR     MessageType = 4
	MessageType_HEARTBEAT MessageType = 5
	MessageType_ACK       MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HELLO",
		2: "QUERY",
		3: "RESULT",
		4: "ERROR",
		5: "HEARTBEAT",
		6: "ACK",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":   0,
		"HELLO":     1,
		"QUERY":     2,
		"RESULT":    3,
		"ERROR":     4,
		"HEARTBEAT": 5,
		"ACK":       6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_proto_agent_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_modules_proto_agent_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{0}
}

type DbType int32

const (
	DbType_MYSQL      DbType = 0
	DbType_POSTGRESQL DbType = 1
	DbType_FIREBIRD   DbType = 2
	DbType_MSSQL      DbType = 3
	DbType_MYSQL_OLD  DbType = 4
)

// Enum value maps for DbType.
var (
	DbType_name = map[int32]string{
		0: "MYSQL",
		1: "POSTGRESQL",
		2: "FIREBIRD",
		3: "MSSQL",
		4: "MYSQL_OLD",
	}
	DbType_value = map[string]int32{
		"MYSQL":      0,
		"POSTGRESQL": 1,
		"FIREBIRD":   2,
		"MSSQL":      3,
		"MYSQL_OLD":  4,
	}
)

func (x DbType) Enum() *DbType {
	p := new(DbType)
	*p = x
	return p
}

func (x DbType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DbType) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_proto_agent_proto_enumTypes[1].Descriptor()
}

func (DbType) Type() protoreflect.EnumType {
	return &file_modules_proto_agent_proto_enumTypes[1]
}

func (x DbType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DbType.Descriptor instead.
func (DbType) EnumDescriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{1}
}

type Table int32

const (
	Table_QPRODUTOS   Table = 0
	Table_QCLIENTES   Table = 1
	Table_QCATEGORIAS Table = 2
	Table_QVENDAS     Table = 3
	Table_QVENDEDORES Table = 4
	Table_QFINANCEIRO Table = 5
	Table_QGENERIC    Table = 6
)

// Enum value maps for Table.
var (
	Table_name = map[int32]string{
		0: "QPRODUTOS",
		1: "QCLIENTES",
		2: "QCATEGORIAS",
		3: "QVENDAS",
		4: "QVENDEDORES",
		5: "QFINANCEIRO",
		6: "QGENERIC",
	}
	Table_value = map[string]int32{
		"QPRODUTOS":   0,
		"QCLIENTES":   1,
		"QCATEGORIAS": 2,
		"QVENDAS":     3,
		"QVENDEDORES": 4,
		"QFINANCEIRO": 5,
		"QGENERIC":    6,
	}
)

func (x Table) Enum() *Table {
	p := new(Table)
	*p = x
	return p
}

func (x Table) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Table) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_proto_agent_proto_enumTypes[2].Descriptor()
}

func (Table) Type() protoreflect.EnumType {
	return &file_modules_proto_agent_proto_enumTypes[2]
}

func (x Table) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Table.Descriptor instead.
func (Table) EnumDescriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{2}
}

type ConnectStatus int32

const (
	ConnectStatus_REJECTED ConnectStatus = 0
	ConnectStatus_ACCEPTED ConnectStatus = 1
)

// Enum value maps for ConnectStatus.
var (
	ConnectStatus_name = map[int32]string{
		0: "REJECTED",
		1: "ACCEPTED",
	}
	ConnectStatus_value = map[string]int32{
		"REJECTED": 0,
		"ACCEPTED": 1,
	}
)

func (x ConnectStatus) Enum() *ConnectStatus {
	p := new(ConnectStatus)
	*p = x
	return p
}

func (x ConnectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_proto_agent_proto_enumTypes[3].Descriptor()
}

func (ConnectStatus) Type() protoreflect.EnumType {
	return &file_modules_proto_agent_proto_enumTypes[3]
}

func (x ConnectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectStatus.Descriptor instead.
func (ConnectStatus) EnumDescriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{3}
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=agent.MessageType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Payload       *AgentPayload          `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // AgentPayload to better perfomance will be on of the options
	Table         Table                  `protobuf:"varint,6,opt,name=table,proto3,enum=agent.Table" json:"table,omitempty"`
	IsLast        bool                   `protobuf:"varint,7,opt,name=isLast,proto3" json:"isLast,omitempty"`
	IsEmpty       bool                   `protobuf:"varint,8,opt,name=isEmpty,proto3" json:"isEmpty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_modules_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *AgentMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *AgentMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentMessage) GetPayload() *AgentPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetTable() Table {
	if x != nil {
		return x.Table
	}
	return Table_QPRODUTOS
}

func (x *AgentMessage) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *AgentMessage) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

type AgentPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*AgentPayload_Produtos
	//	*AgentPayload_Vendas
	//	*AgentPayload_Clientes
	//	*AgentPayload_Categorias
	//	*AgentPayload_Vendedores
	//	*AgentPayload_Financeiros
	//	*AgentPayload_GenericReturn
	//	*AgentPayload_QueryRequest
	//	*AgentPayload_Erros
	//	*AgentPayload_AckReturn
	Data          isAgentPayload_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPayload) Reset() {
	*x = AgentPayload{}
	mi := &file_modules_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPayload) ProtoMessage() {}

func (x *AgentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPayload.ProtoReflect.Descriptor instead.
func (*AgentPayload) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentPayload) GetData() isAgentPayload_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentPayload) GetProdutos() *Produtos {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Produtos); ok {
			return x.Produtos
		}
	}
	return nil
}

func (x *AgentPayload) GetVendas() *Vendas {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Vendas); ok {
			return x.Vendas
		}
	}
	return nil
}

func (x *AgentPayload) GetClientes() *Clientes {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Clientes); ok {
			return x.Clientes
		}
	}
	return nil
}

func (x *AgentPayload) GetCategorias() *Categorias {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Categorias); ok {
			return x.Categorias
		}
	}
	return nil
}

func (x *AgentPayload) GetVendedores() *Vendedores {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Vendedores); ok {
			return x.Vendedores
		}
	}
	return nil
}

func (x *AgentPayload) GetFinanceiros() *Financeiros {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Financeiros); ok {
			return x.Financeiros
		}
	}
	return nil
}

func (x *AgentPayload) GetGenericReturn() *structpb.ListValue {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_GenericReturn); ok {
			return x.GenericReturn
		}
	}
	return nil
}

func (x *AgentPayload) GetQueryRequest() *Query {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *AgentPayload) GetErros() *Erros {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_Erros); ok {
			return x.Erros
		}
	}
	return nil
}

func (x *AgentPayload) GetAckReturn() *ACKReturn {
	if x != nil {
		if x, ok := x.Data.(*AgentPayload_AckReturn); ok {
			return x.AckReturn
		}
	}
	return nil
}

type isAgentPayload_Data interface {
	isAgentPayload_Data()
}

type AgentPayload_Produtos struct {
	Produtos *Produtos `protobuf:"bytes,1,opt,name=produtos,proto3,oneof"`
}

type AgentPayload_Vendas struct {
	Vendas *Vendas `protobuf:"bytes,2,opt,name=vendas,proto3,oneof"`
}

type AgentPayload_Clientes struct {
	Clientes *Clientes `protobuf:"bytes,3,opt,name=clientes,proto3,oneof"`
}

type AgentPayload_Categorias struct {
	Categorias *Categorias `protobuf:"bytes,4,opt,name=categorias,proto3,oneof"`
}

type AgentPayload_Vendedores struct {
	Vendedores *Vendedores `protobuf:"bytes,5,opt,name=vendedores,proto3,oneof"`
}

type AgentPayload_Financeiros struct {
	Financeiros *Financeiros `protobuf:"bytes,6,opt,name=financeiros,proto3,oneof"`
}

type AgentPayload_GenericReturn struct {
	GenericReturn *structpb.ListValue `protobuf:"bytes,7,opt,name=generic_return,json=genericReturn,proto3,oneof"`
}

type AgentPayload_QueryRequest struct {
	QueryRequest *Query `protobuf:"bytes,8,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type AgentPayload_Erros struct {
	Erros *Erros `protobuf:"bytes,9,opt,name=erros,proto3,oneof"`
}

type AgentPayload_AckReturn struct {
	AckReturn *ACKReturn `protobuf:"bytes,10,opt,name=ack_return,json=ackReturn,proto3,oneof"`
}

func (*AgentPayload_Produtos) isAgentPayload_Data() {}

func (*AgentPayload_Vendas) isAgentPayload_Data() {}

func (*AgentPayload_Clientes) isAgentPayload_Data() {}

func (*AgentPayload_Categorias) isAgentPayload_Data() {}

func (*AgentPayload_Vendedores) isAgentPayload_Data() {}

func (*AgentPayload_Financeiros) isAgentPayload_Data() {}

func (*AgentPayload_GenericReturn) isAgentPayload_Data() {}

func (*AgentPayload_QueryRequest) isAgentPayload_Data() {}

func (*AgentPayload_Erros) isAgentPayload_Data() {}

func (*AgentPayload_AckReturn) isAgentPayload_Data() {}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_modules_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Query) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ACKReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ConnectStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=agent.ConnectStatus" json:"status,omitempty"`
	ConnectedUser *ConnectedUser         `protobuf:"bytes,2,opt,name=connected_user,json=connectedUser,proto3" json:"connected_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACKReturn) Reset() {
	*x = ACKReturn{}
	mi := &file_modules_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACKReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACKReturn) ProtoMessage() {}

func (x *ACKReturn) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACKReturn.ProtoReflect.Descriptor instead.
func (*ACKReturn) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ACKReturn) GetStatus() ConnectStatus {
	if x != nil {
		return x.Status
	}
	return ConnectStatus_REJECTED
}

func (x *ACKReturn) GetConnectedUser() *ConnectedUser {
	if x != nil {
		return x.ConnectedUser
	}
	return nil
}

type ConnectedUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        DbType                 `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3,enum=agent.DbType" json:"db_type,omitempty"`
	UseApi        bool                   `protobuf:"varint,2,opt,name=use_api,json=useApi,proto3" json:"use_api,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	Domainws      string                 `protobuf:"bytes,4,opt,name=domainws,proto3" json:"domainws,omitempty"`
	Cronjob       string                 `protobuf:"bytes,5,opt,name=cronjob,proto3" json:"cronjob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedUser) Reset() {
	*x = ConnectedUser{}
	mi := &file_modules_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedUser) ProtoMessage() {}

func (x *ConnectedUser) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedUser.ProtoReflect.Descriptor instead.
func (*ConnectedUser) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectedUser) GetDbType() DbType {
	if x != nil {
		return x.DbType
	}
	return DbType_MYSQL
}

func (x *ConnectedUser) GetUseApi() bool {
	if x != nil {
		return x.UseApi
	}
	return false
}

func (x *ConnectedUser) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ConnectedUser) GetDomainws() string {
	if x != nil {
		return x.Domainws
	}
	return ""
}

func (x *ConnectedUser) GetCronjob() string {
	if x != nil {
		return x.Cronjob
	}
	return ""
}

type Erros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         []*Error               `protobuf:"bytes,1,rep,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Erros) Reset() {
	*x = Erros{}
	mi := &file_modules_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Erros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Erros) ProtoMessage() {}

func (x *Erros) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Erros.ProtoReflect.Descriptor instead.
func (*Erros) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Erros) GetError() []*Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_modules_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// produtos ---
type Produtos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Produto             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Produtos) Reset() {
	*x = Produtos{}
	mi := &file_modules_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Produtos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produtos) ProtoMessage() {}

func (x *Produtos) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produtos.ProtoReflect.Descriptor instead.
func (*Produtos) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Produtos) GetItems() []*Produto {
	if x != nil {
		return x.Items
	}
	return nil
}

type Produto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdExterno     string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Codigo        string                 `protobuf:"bytes,3,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Valor         float32                `protobuf:"fixed32,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Duracao       string                 `protobuf:"bytes,5,opt,name=duracao,proto3" json:"duracao,omitempty"`
	NoBuyback     bool                   `protobuf:"varint,6,opt,name=no_buyback,json=noBuyback,proto3" json:"no_buyback,omitempty"`
	Comissao      int32                  `protobuf:"varint,7,opt,name=comissao,proto3" json:"comissao,omitempty"`
	Categoria     string                 `protobuf:"bytes,8,opt,name=categoria,proto3" json:"categoria,omitempty"`
	NomeCategoria string                 `protobuf:"bytes,9,opt,name=nome_categoria,json=nomeCategoria,proto3" json:"nome_categoria,omitempty"`
	Descricao     string                 `protobuf:"bytes,10,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Estoque       string                 `protobuf:"bytes,11,opt,name=estoque,proto3" json:"estoque,omitempty"`
	ContarEstoque bool                   `protobuf:"varint,12,opt,name=contar_estoque,json=contarEstoque,proto3" json:"contar_estoque,omitempty"`
	Ativo         bool                   `protobuf:"varint,13,opt,name=ativo,proto3" json:"ativo,omitempty"`
	Complemento   string                 `protobuf:"bytes,14,opt,name=complemento,proto3" json:"complemento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Produto) Reset() {
	*x = Produto{}
	mi := &file_modules_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Produto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produto) ProtoMessage() {}

func (x *Produto) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produto.ProtoReflect.Descriptor instead.
func (*Produto) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Produto) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *Produto) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Produto) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *Produto) GetValor() float32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Produto) GetDuracao() string {
	if x != nil {
		return x.Duracao
	}
	return ""
}

func (x *Produto) GetNoBuyback() bool {
	if x != nil {
		return x.NoBuyback
	}
	return false
}

func (x *Produto) GetComissao() int32 {
	if x != nil {
		return x.Comissao
	}
	return 0
}

func (x *Produto) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Produto) GetNomeCategoria() string {
	if x != nil {
		return x.NomeCategoria
	}
	return ""
}

func (x *Produto) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Produto) GetEstoque() string {
	if x != nil {
		return x.Estoque
	}
	return ""
}

func (x *Produto) GetContarEstoque() bool {
	if x != nil {
		return x.ContarEstoque
	}
	return false
}

func (x *Produto) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Produto) GetComplemento() string {
	if x != nil {
		return x.Complemento
	}
	return ""
}

// clientes ---
type Clientes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Cliente             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clientes) Reset() {
	*x = Clientes{}
	mi := &file_modules_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clientes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clientes) ProtoMessage() {}

func (x *Clientes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clientes.ProtoReflect.Descriptor instead.
func (*Clientes) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Clientes) GetItems() []*Cliente {
	if x != nil {
		return x.Items
	}
	return nil
}

type Cliente struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdExterno     string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Referencia    string                 `protobuf:"bytes,3,opt,name=referencia,proto3" json:"referencia,omitempty"`
	Whatsapp      string                 `protobuf:"bytes,4,opt,name=whatsapp,proto3" json:"whatsapp,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Aniversario   string                 `protobuf:"bytes,6,opt,name=aniversario,proto3" json:"aniversario,omitempty"`
	PjOuPf        string                 `protobuf:"bytes,7,opt,name=pj_ou_pf,json=pjOuPf,proto3" json:"pj_ou_pf,omitempty"`
	CpfCnpj       string                 `protobuf:"bytes,8,opt,name=cpf_cnpj,json=cpfCnpj,proto3" json:"cpf_cnpj,omitempty"`
	Endereco      string                 `protobuf:"bytes,9,opt,name=endereco,proto3" json:"endereco,omitempty"`
	Num           string                 `protobuf:"bytes,10,opt,name=num,proto3" json:"num,omitempty"`
	Bairro        string                 `protobuf:"bytes,11,opt,name=bairro,proto3" json:"bairro,omitempty"`
	Cidade        string                 `protobuf:"bytes,12,opt,name=cidade,proto3" json:"cidade,omitempty"`
	Idade         int32                  `protobuf:"varint,13,opt,name=idade,proto3" json:"idade,omitempty"`
	Sexo          string                 `protobuf:"bytes,14,opt,name=sexo,proto3" json:"sexo,omitempty"`
	VendedorId    int32                  `protobuf:"varint,15,opt,name=vendedor_id,json=vendedorId,proto3" json:"vendedor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cliente) Reset() {
	*x = Cliente{}
	mi := &file_modules_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cliente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cliente) ProtoMessage() {}

func (x *Cliente) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cliente.ProtoReflect.Descriptor instead.
func (*Cliente) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Cliente) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *Cliente) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Cliente) GetReferencia() string {
	if x != nil {
		return x.Referencia
	}
	return ""
}

func (x *Cliente) GetWhatsapp() string {
	if x != nil {
		return x.Whatsapp
	}
	return ""
}

func (x *Cliente) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Cliente) GetAniversario() string {
	if x != nil {
		return x.Aniversario
	}
	return ""
}

func (x *Cliente) GetPjOuPf() string {
	if x != nil {
		return x.PjOuPf
	}
	return ""
}

func (x *Cliente) GetCpfCnpj() string {
	if x != nil {
		return x.CpfCnpj
	}
	return ""
}

func (x *Cliente) GetEndereco() string {
	if x != nil {
		return x.Endereco
	}
	return ""
}

func (x *Cliente) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *Cliente) GetBairro() string {
	if x != nil {
		return x.Bairro
	}
	return ""
}

func (x *Cliente) GetCidade() string {
	if x != nil {
		return x.Cidade
	}
	return ""
}

func (x *Cliente) GetIdade() int32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

func (x *Cliente) GetSexo() string {
	if x != nil {
		return x.Sexo
	}
	return ""
}

func (x *Cliente) GetVendedorId() int32 {
	if x != nil {
		return x.VendedorId
	}
	return 0
}

// categorias ---
type Categorias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Categoria           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categorias) Reset() {
	*x = Categorias{}
	mi := &file_modules_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categorias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categorias) ProtoMessage() {}

func (x *Categorias) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categorias.ProtoReflect.Descriptor instead.
func (*Categorias) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Categorias) GetItems() []*Categoria {
	if x != nil {
		return x.Items
	}
	return nil
}

type Categoria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdExterno     string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categoria) Reset() {
	*x = Categoria{}
	mi := &file_modules_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categoria) ProtoMessage() {}

func (x *Categoria) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categoria.ProtoReflect.Descriptor instead.
func (*Categoria) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Categoria) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *Categoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

// vendedores ---
type Vendedores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Vendedor            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vendedores) Reset() {
	*x = Vendedores{}
	mi := &file_modules_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendedores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendedores) ProtoMessage() {}

func (x *Vendedores) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendedores.ProtoReflect.Descriptor instead.
func (*Vendedores) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *Vendedores) GetItems() []*Vendedor {
	if x != nil {
		return x.Items
	}
	return nil
}

type Vendedor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdExterno       string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	Nome            string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Codigo          string                 `protobuf:"bytes,3,opt,name=codigo,proto3" json:"codigo,omitempty"`
	TodasPermissoes bool                   `protobuf:"varint,4,opt,name=todas_permissoes,json=todasPermissoes,proto3" json:"todas_permissoes,omitempty"`
	Ativo           bool                   `protobuf:"varint,5,opt,name=ativo,proto3" json:"ativo,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Vendedor) Reset() {
	*x = Vendedor{}
	mi := &file_modules_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendedor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendedor) ProtoMessage() {}

func (x *Vendedor) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendedor.ProtoReflect.Descriptor instead.
func (*Vendedor) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Vendedor) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *Vendedor) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Vendedor) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *Vendedor) GetTodasPermissoes() bool {
	if x != nil {
		return x.TodasPermissoes
	}
	return false
}

func (x *Vendedor) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

// vendedores ---
// vendas ---
type Vendas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Venda               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vendas) Reset() {
	*x = Vendas{}
	mi := &file_modules_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendas) ProtoMessage() {}

func (x *Vendas) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendas.ProtoReflect.Descriptor instead.
func (*Vendas) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *Vendas) GetItems() []*Venda {
	if x != nil {
		return x.Items
	}
	return nil
}

type Venda struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdExterno       string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	Empresa         int32                  `protobuf:"varint,2,opt,name=empresa,proto3" json:"empresa,omitempty"`
	Cliente         string                 `protobuf:"bytes,3,opt,name=cliente,proto3" json:"cliente,omitempty"`
	Vendedor        string                 `protobuf:"bytes,4,opt,name=vendedor,proto3" json:"vendedor,omitempty"`
	DataCompra      string                 `protobuf:"bytes,5,opt,name=data_compra,json=dataCompra,proto3" json:"data_compra,omitempty"`
	TotalCompra     float32                `protobuf:"fixed32,6,opt,name=total_compra,json=totalCompra,proto3" json:"total_compra,omitempty"`
	ValorLiquido    float32                `protobuf:"fixed32,7,opt,name=valor_liquido,json=valorLiquido,proto3" json:"valor_liquido,omitempty"`
	TipoPagamento   string                 `protobuf:"bytes,8,opt,name=tipo_pagamento,json=tipoPagamento,proto3" json:"tipo_pagamento,omitempty"`
	Recorrente      bool                   `protobuf:"varint,9,opt,name=recorrente,proto3" json:"recorrente,omitempty"`
	Parcelas        int32                  `protobuf:"varint,10,opt,name=parcelas,proto3" json:"parcelas,omitempty"`
	Entrada         float32                `protobuf:"fixed32,11,opt,name=entrada,proto3" json:"entrada,omitempty"`
	DataVencimento  string                 `protobuf:"bytes,12,opt,name=data_vencimento,json=dataVencimento,proto3" json:"data_vencimento,omitempty"`
	MetodoPagamento string                 `protobuf:"bytes,13,opt,name=metodo_pagamento,json=metodoPagamento,proto3" json:"metodo_pagamento,omitempty"`
	Orcamento       bool                   `protobuf:"varint,14,opt,name=orcamento,proto3" json:"orcamento,omitempty"`
	OferecerDenovo  int32                  `protobuf:"varint,15,opt,name=oferecer_denovo,json=oferecerDenovo,proto3" json:"oferecer_denovo,omitempty"`
	ProdutosVenda   []*ProdutosVendas      `protobuf:"bytes,16,rep,name=produtos_venda,json=produtosVenda,proto3" json:"produtos_venda,omitempty"`
	Observacao      string                 `protobuf:"bytes,17,opt,name=observacao,proto3" json:"observacao,omitempty"`
	DatasVencimento []*DatasVencimento     `protobuf:"bytes,18,rep,name=datas_vencimento,json=datasVencimento,proto3" json:"datas_vencimento,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Venda) Reset() {
	*x = Venda{}
	mi := &file_modules_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Venda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venda) ProtoMessage() {}

func (x *Venda) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venda.ProtoReflect.Descriptor instead.
func (*Venda) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *Venda) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *Venda) GetEmpresa() int32 {
	if x != nil {
		return x.Empresa
	}
	return 0
}

func (x *Venda) GetCliente() string {
	if x != nil {
		return x.Cliente
	}
	return ""
}

func (x *Venda) GetVendedor() string {
	if x != nil {
		return x.Vendedor
	}
	return ""
}

func (x *Venda) GetDataCompra() string {
	if x != nil {
		return x.DataCompra
	}
	return ""
}

func (x *Venda) GetTotalCompra() float32 {
	if x != nil {
		return x.TotalCompra
	}
	return 0
}

func (x *Venda) GetValorLiquido() float32 {
	if x != nil {
		return x.ValorLiquido
	}
	return 0
}

func (x *Venda) GetTipoPagamento() string {
	if x != nil {
		return x.TipoPagamento
	}
	return ""
}

func (x *Venda) GetRecorrente() bool {
	if x != nil {
		return x.Recorrente
	}
	return false
}

func (x *Venda) GetParcelas() int32 {
	if x != nil {
		return x.Parcelas
	}
	return 0
}

func (x *Venda) GetEntrada() float32 {
	if x != nil {
		return x.Entrada
	}
	return 0
}

func (x *Venda) GetDataVencimento() string {
	if x != nil {
		return x.DataVencimento
	}
	return ""
}

func (x *Venda) GetMetodoPagamento() string {
	if x != nil {
		return x.MetodoPagamento
	}
	return ""
}

func (x *Venda) GetOrcamento() bool {
	if x != nil {
		return x.Orcamento
	}
	return false
}

func (x *Venda) GetOferecerDenovo() int32 {
	if x != nil {
		return x.OferecerDenovo
	}
	return 0
}

func (x *Venda) GetProdutosVenda() []*ProdutosVendas {
	if x != nil {
		return x.ProdutosVenda
	}
	return nil
}

func (x *Venda) GetObservacao() string {
	if x != nil {
		return x.Observacao
	}
	return ""
}

func (x *Venda) GetDatasVencimento() []*DatasVencimento {
	if x != nil {
		return x.DatasVencimento
	}
	return nil
}

type ProdutosVendas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProdutoId     string                 `protobuf:"bytes,1,opt,name=produto_id,json=produtoId,proto3" json:"produto_id,omitempty"`
	Quantidade    string                 `protobuf:"bytes,2,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	ValorUnitario string                 `protobuf:"bytes,3,opt,name=valor_unitario,json=valorUnitario,proto3" json:"valor_unitario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProdutosVendas) Reset() {
	*x = ProdutosVendas{}
	mi := &file_modules_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProdutosVendas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdutosVendas) ProtoMessage() {}

func (x *ProdutosVendas) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdutosVendas.ProtoReflect.Descriptor instead.
func (*ProdutosVendas) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ProdutosVendas) GetProdutoId() string {
	if x != nil {
		return x.ProdutoId
	}
	return ""
}

func (x *ProdutosVendas) GetQuantidade() string {
	if x != nil {
		return x.Quantidade
	}
	return ""
}

func (x *ProdutosVendas) GetValorUnitario() string {
	if x != nil {
		return x.ValorUnitario
	}
	return ""
}

type DatasVencimento struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DataVencimento string                 `protobuf:"bytes,1,opt,name=data_vencimento,json=dataVencimento,proto3" json:"data_vencimento,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatasVencimento) Reset() {
	*x = DatasVencimento{}
	mi := &file_modules_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasVencimento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasVencimento) ProtoMessage() {}

func (x *DatasVencimento) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasVencimento.ProtoReflect.Descriptor instead.
func (*DatasVencimento) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *DatasVencimento) GetDataVencimento() string {
	if x != nil {
		return x.DataVencimento
	}
	return ""
}

// vendedores ---
type Financeiros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Financeiro          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Financeiros) Reset() {
	*x = Financeiros{}
	mi := &file_modules_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Financeiros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Financeiros) ProtoMessage() {}

func (x *Financeiros) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Financeiros.ProtoReflect.Descriptor instead.
func (*Financeiros) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *Financeiros) GetItems() []*Financeiro {
	if x != nil {
		return x.Items
	}
	return nil
}

type Financeiro struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdExterno          string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	Cliente            string                 `protobuf:"bytes,2,opt,name=cliente,proto3" json:"cliente,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ValorTotal         float32                `protobuf:"fixed32,4,opt,name=valor_total,json=valorTotal,proto3" json:"valor_total,omitempty"`
	Parcelas           int32                  `protobuf:"varint,5,opt,name=parcelas,proto3" json:"parcelas,omitempty"`
	ValorParcela       float32                `protobuf:"fixed32,6,opt,name=valor_parcela,json=valorParcela,proto3" json:"valor_parcela,omitempty"`
	DataVencimento     string                 `protobuf:"bytes,7,opt,name=data_vencimento,json=dataVencimento,proto3" json:"data_vencimento,omitempty"`
	DataPersonalizadas bool                   `protobuf:"varint,8,opt,name=data_personalizadas,json=dataPersonalizadas,proto3" json:"data_personalizadas,omitempty"`
	InfosCobranca      []*InfosObranca        `protobuf:"bytes,9,rep,name=infos_cobranca,json=infosCobranca,proto3" json:"infos_cobranca,omitempty"`
	Recorrente         bool                   `protobuf:"varint,10,opt,name=recorrente,proto3" json:"recorrente,omitempty"`
	Venda              string                 `protobuf:"bytes,11,opt,name=venda,proto3" json:"venda,omitempty"`
	Media              string                 `protobuf:"bytes,12,opt,name=media,proto3" json:"media,omitempty"`
	TituloCobranca     string                 `protobuf:"bytes,13,opt,name=titulo_cobranca,json=tituloCobranca,proto3" json:"titulo_cobranca,omitempty"`
	Ativo              bool                   `protobuf:"varint,14,opt,name=ativo,proto3" json:"ativo,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Financeiro) Reset() {
	*x = Financeiro{}
	mi := &file_modules_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Financeiro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Financeiro) ProtoMessage() {}

func (x *Financeiro) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Financeiro.ProtoReflect.Descriptor instead.
func (*Financeiro) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *Financeiro) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *Financeiro) GetCliente() string {
	if x != nil {
		return x.Cliente
	}
	return ""
}

func (x *Financeiro) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Financeiro) GetValorTotal() float32 {
	if x != nil {
		return x.ValorTotal
	}
	return 0
}

func (x *Financeiro) GetParcelas() int32 {
	if x != nil {
		return x.Parcelas
	}
	return 0
}

func (x *Financeiro) GetValorParcela() float32 {
	if x != nil {
		return x.ValorParcela
	}
	return 0
}

func (x *Financeiro) GetDataVencimento() string {
	if x != nil {
		return x.DataVencimento
	}
	return ""
}

func (x *Financeiro) GetDataPersonalizadas() bool {
	if x != nil {
		return x.DataPersonalizadas
	}
	return false
}

func (x *Financeiro) GetInfosCobranca() []*InfosObranca {
	if x != nil {
		return x.InfosCobranca
	}
	return nil
}

func (x *Financeiro) GetRecorrente() bool {
	if x != nil {
		return x.Recorrente
	}
	return false
}

func (x *Financeiro) GetVenda() string {
	if x != nil {
		return x.Venda
	}
	return ""
}

func (x *Financeiro) GetMedia() string {
	if x != nil {
		return x.Media
	}
	return ""
}

func (x *Financeiro) GetTituloCobranca() string {
	if x != nil {
		return x.TituloCobranca
	}
	return ""
}

func (x *Financeiro) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

type InfosObranca struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdExterno      string                 `protobuf:"bytes,1,opt,name=id_externo,json=idExterno,proto3" json:"id_externo,omitempty"`
	ValorParcela   float32                `protobuf:"fixed32,2,opt,name=valor_parcela,json=valorParcela,proto3" json:"valor_parcela,omitempty"`
	DataVencimento string                 `protobuf:"bytes,3,opt,name=data_vencimento,json=dataVencimento,proto3" json:"data_vencimento,omitempty"`
	DataCriacao    string                 `protobuf:"bytes,4,opt,name=data_criacao,json=dataCriacao,proto3" json:"data_criacao,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfosObranca) Reset() {
	*x = InfosObranca{}
	mi := &file_modules_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfosObranca) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfosObranca) ProtoMessage() {}

func (x *InfosObranca) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfosObranca.ProtoReflect.Descriptor instead.
func (*InfosObranca) Descriptor() ([]byte, []int) {
	return file_modules_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *InfosObranca) GetIdExterno() string {
	if x != nil {
		return x.IdExterno
	}
	return ""
}

func (x *InfosObranca) GetValorParcela() float32 {
	if x != nil {
		return x.ValorParcela
	}
	return 0
}

func (x *InfosObranca) GetDataVencimento() string {
	if x != nil {
		return x.DataVencimento
	}
	return ""
}

func (x *InfosObranca) GetDataCriacao() string {
	if x != nil {
		return x.DataCriacao
	}
	return ""
}

func (x *InfosObranca) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_modules_proto_agent_proto protoreflect.FileDescriptor

const file_modules_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x19modules/proto/agent.proto\x12\x05agent\x1a\x1cgoogle/protobuf/struct.proto\"\x8b\x02\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.agent.MessageTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12-\n" +
	"\apayload\x18\x05 \x01(\v2\x13.agent.AgentPayloadR\apayload\x12\"\n" +
	"\x05table\x18\x06 \x01(\x0e2\f.agent.TableR\x05table\x12\x16\n" +
	"\x06isLast\x18\a \x01(\bR\x06isLast\x12\x18\n" +
	"\aisEmpty\x18\b \x01(\bR\aisEmpty\"\x92\x04\n" +
	"\fAgentPayload\x12-\n" +
	"\bprodutos\x18\x01 \x01(\v2\x0f.agent.ProdutosH\x00R\bprodutos\x12'\n" +
	"\x06vendas\x18\x02 \x01(\v2\r.agent.VendasH\x00R\x06vendas\x12-\n" +
	"\bclientes\x18\x03 \x01(\v2\x0f.agent.ClientesH\x00R\bclientes\x123\n" +
	"\n" +
	"categorias\x18\x04 \x01(\v2\x11.agent.CategoriasH\x00R\n" +
	"categorias\x123\n" +
	"\n" +
	"vendedores\x18\x05 \x01(\v2\x11.agent.VendedoresH\x00R\n" +
	"vendedores\x126\n" +
	"\vfinanceiros\x18\x06 \x01(\v2\x12.agent.FinanceirosH\x00R\vfinanceiros\x12C\n" +
	"\x0egeneric_return\x18\a \x01(\v2\x1a.google.protobuf.ListValueH\x00R\rgenericReturn\x123\n" +
	"\rquery_request\x18\b \x01(\v2\f.agent.QueryH\x00R\fqueryRequest\x12$\n" +
	"\x05erros\x18\t \x01(\v2\f.agent.ErrosH\x00R\x05erros\x121\n" +
	"\n" +
	"ack_return\x18\n" +
	" \x01(\v2\x10.agent.ACKReturnH\x00R\tackReturnB\x06\n" +
	"\x04data\";\n" +
	"\x05Query\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tbatchSize\x18\x02 \x01(\x05R\tbatchSize\"v\n" +
	"\tACKReturn\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.agent.ConnectStatusR\x06status\x12;\n" +
	"\x0econnected_user\x18\x02 \x01(\v2\x14.agent.ConnectedUserR\rconnectedUser\"\xa8\x01\n" +
	"\rConnectedUser\x12'\n" +
	"\adb_type\x18\x01 \x01(\x0e2\x0e.agent.Db_typeR\x06dbType\x12\x17\n" +
	"\ause_api\x18\x02 \x01(\bR\x06useApi\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\x12\x1a\n" +
	"\bdomainws\x18\x04 \x01(\tR\bdomainws\x12\x18\n" +
	"\acronjob\x18\x05 \x01(\tR\acronjob\"+\n" +
	"\x05Erros\x12\"\n" +
	"\x05error\x18\x01 \x03(\v2\f.agent.ErrorR\x05error\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"0\n" +
	"\bProdutos\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.agent.ProdutoR\x05items\"\x9b\x03\n" +
	"\aProduto\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x16\n" +
	"\x06codigo\x18\x03 \x01(\tR\x06codigo\x12\x14\n" +
	"\x05valor\x18\x04 \x01(\x02R\x05valor\x12\x18\n" +
	"\aduracao\x18\x05 \x01(\tR\aduracao\x12\x1d\n" +
	"\n" +
	"no_buyback\x18\x06 \x01(\bR\tnoBuyback\x12\x1a\n" +
	"\bcomissao\x18\a \x01(\x05R\bcomissao\x12\x1c\n" +
	"\tcategoria\x18\b \x01(\tR\tcategoria\x12%\n" +
	"\x0enome_categoria\x18\t \x01(\tR\rnomeCategoria\x12\x1c\n" +
	"\tdescricao\x18\n" +
	" \x01(\tR\tdescricao\x12\x18\n" +
	"\aestoque\x18\v \x01(\tR\aestoque\x12%\n" +
	"\x0econtar_estoque\x18\f \x01(\bR\rcontarEstoque\x12\x14\n" +
	"\x05ativo\x18\r \x01(\bR\x05ativo\x12 \n" +
	"\vcomplemento\x18\x0e \x01(\tR\vcomplemento\"0\n" +
	"\bClientes\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.agent.ClienteR\x05items\"\x8e\x03\n" +
	"\aCliente\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1e\n" +
	"\n" +
	"referencia\x18\x03 \x01(\tR\n" +
	"referencia\x12\x1a\n" +
	"\bwhatsapp\x18\x04 \x01(\tR\bwhatsapp\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12 \n" +
	"\vaniversario\x18\x06 \x01(\tR\vaniversario\x12\x18\n" +
	"\bpj_ou_pf\x18\a \x01(\tR\x06pjOuPf\x12\x19\n" +
	"\bcpf_cnpj\x18\b \x01(\tR\acpfCnpj\x12\x1a\n" +
	"\bendereco\x18\t \x01(\tR\bendereco\x12\x10\n" +
	"\x03num\x18\n" +
	" \x01(\tR\x03num\x12\x16\n" +
	"\x06bairro\x18\v \x01(\tR\x06bairro\x12\x16\n" +
	"\x06cidade\x18\f \x01(\tR\x06cidade\x12\x14\n" +
	"\x05idade\x18\r \x01(\x05R\x05idade\x12\x12\n" +
	"\x04sexo\x18\x0e \x01(\tR\x04sexo\x12\x1f\n" +
	"\vvendedor_id\x18\x0f \x01(\x05R\n" +
	"vendedorId\"4\n" +
	"\n" +
	"Categorias\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.agent.CategoriaR\x05items\">\n" +
	"\tCategoria\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\"3\n" +
	"\n" +
	"Vendedores\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.agent.VendedorR\x05items\"\x96\x01\n" +
	"\bVendedor\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x16\n" +
	"\x06codigo\x18\x03 \x01(\tR\x06codigo\x12)\n" +
	"\x10todas_permissoes\x18\x04 \x01(\bR\x0ftodasPermissoes\x12\x14\n" +
	"\x05ativo\x18\x05 \x01(\bR\x05ativo\",\n" +
	"\x06Vendas\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.agent.VendaR\x05items\"\x9a\x05\n" +
	"\x05Venda\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12\x18\n" +
	"\aempresa\x18\x02 \x01(\x05R\aempresa\x12\x18\n" +
	"\acliente\x18\x03 \x01(\tR\acliente\x12\x1a\n" +
	"\bvendedor\x18\x04 \x01(\tR\bvendedor\x12\x1f\n" +
	"\vdata_compra\x18\x05 \x01(\tR\n" +
	"dataCompra\x12!\n" +
	"\ftotal_compra\x18\x06 \x01(\x02R\vtotalCompra\x12#\n" +
	"\rvalor_liquido\x18\a \x01(\x02R\fvalorLiquido\x12%\n" +
	"\x0etipo_pagamento\x18\b \x01(\tR\rtipoPagamento\x12\x1e\n" +
	"\n" +
	"recorrente\x18\t \x01(\bR\n" +
	"recorrente\x12\x1a\n" +
	"\bparcelas\x18\n" +
	" \x01(\x05R\bparcelas\x12\x18\n" +
	"\aentrada\x18\v \x01(\x02R\aentrada\x12'\n" +
	"\x0fdata_vencimento\x18\f \x01(\tR\x0edataVencimento\x12)\n" +
	"\x10metodo_pagamento\x18\r \x01(\tR\x0fmetodoPagamento\x12\x1c\n" +
	"\torcamento\x18\x0e \x01(\bR\torcamento\x12'\n" +
	"\x0foferecer_denovo\x18\x0f \x01(\x05R\x0eoferecerDenovo\x12=\n" +
	"\x0eprodutos_venda\x18\x10 \x03(\v2\x16.agent.Produtos_vendasR\rprodutosVenda\x12\x1e\n" +
	"\n" +
	"observacao\x18\x11 \x01(\tR\n" +
	"observacao\x12B\n" +
	"\x10datas_vencimento\x18\x12 \x03(\v2\x17.agent.Datas_vencimentoR\x0fdatasVencimento\"w\n" +
	"\x0fProdutos_vendas\x12\x1d\n" +
	"\n" +
	"produto_id\x18\x01 \x01(\tR\tprodutoId\x12\x1e\n" +
	"\n" +
	"quantidade\x18\x02 \x01(\tR\n" +
	"quantidade\x12%\n" +
	"\x0evalor_unitario\x18\x03 \x01(\tR\rvalorUnitario\";\n" +
	"\x10Datas_vencimento\x12'\n" +
	"\x0fdata_vencimento\x18\x01 \x01(\tR\x0edataVencimento\"6\n" +
	"\vFinanceiros\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.agent.FinanceiroR\x05items\"\xe1\x03\n" +
	"\n" +
	"Financeiro\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12\x18\n" +
	"\acliente\x18\x02 \x01(\tR\acliente\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vvalor_total\x18\x04 \x01(\x02R\n" +
	"valorTotal\x12\x1a\n" +
	"\bparcelas\x18\x05 \x01(\x05R\bparcelas\x12#\n" +
	"\rvalor_parcela\x18\x06 \x01(\x02R\fvalorParcela\x12'\n" +
	"\x0fdata_vencimento\x18\a \x01(\tR\x0edataVencimento\x12/\n" +
	"\x13data_personalizadas\x18\b \x01(\bR\x12dataPersonalizadas\x12;\n" +
	"\x0einfos_cobranca\x18\t \x03(\v2\x14.agent.Infos_obrancaR\rinfosCobranca\x12\x1e\n" +
	"\n" +
	"recorrente\x18\n" +
	" \x01(\bR\n" +
	"recorrente\x12\x14\n" +
	"\x05venda\x18\v \x01(\tR\x05venda\x12\x14\n" +
	"\x05media\x18\f \x01(\tR\x05media\x12'\n" +
	"\x0ftitulo_cobranca\x18\r \x01(\tR\x0etituloCobranca\x12\x14\n" +
	"\x05ativo\x18\x0e \x01(\bR\x05ativo\"\xb7\x01\n" +
	"\rInfos_obranca\x12\x1d\n" +
	"\n" +
	"id_externo\x18\x01 \x01(\tR\tidExterno\x12#\n" +
	"\rvalor_parcela\x18\x02 \x01(\x02R\fvalorParcela\x12'\n" +
	"\x0fdata_vencimento\x18\x03 \x01(\tR\x0edataVencimento\x12!\n" +
	"\fdata_criacao\x18\x04 \x01(\tR\vdataCriacao\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status*_\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05HELLO\x10\x01\x12\t\n" +
	"\x05QUERY\x10\x02\x12\n" +
	"\n" +
	"\x06RESULT\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\r\n" +
	"\tHEARTBEAT\x10\x05\x12\a\n" +
	"\x03ACK\x10\x06*L\n" +
	"\aDb_type\x12\t\n" +
	"\x05MYSQL\x10\x00\x12\x0e\n" +
	"\n" +
	"POSTGRESQL\x10\x01\x12\f\n" +
	"\bFIREBIRD\x10\x02\x12\t\n" +
	"\x05MSSQL\x10\x03\x12\r\n" +
	"\tMYSQL_OLD\x10\x04*s\n" +
	"\x05Table\x12\r\n" +
	"\tQPRODUTOS\x10\x00\x12\r\n" +
	"\tQCLIENTES\x10\x01\x12\x0f\n" +
	"\vQCATEGORIAS\x10\x02\x12\v\n" +
	"\aQVENDAS\x10\x03\x12\x0f\n" +
	"\vQVENDEDORES\x10\x04\x12\x0f\n" +
	"\vQFINANCEIRO\x10\x05\x12\f\n" +
	"\bQGENERIC\x10\x06*+\n" +
	"\rConnectStatus\x12\f\n" +
	"\bREJECTED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x012G\n" +
	"\fAgentService\x127\n" +
	"\aConnect\x12\x13.agent.AgentMessage\x1a\x13.agent.AgentMessage(\x010\x01B\x17Z\x15modules/proto/agentpbb\x06proto3"

var (
	file_modules_proto_agent_proto_rawDescOnce sync.Once
	file_modules_proto_agent_proto_rawDescData []byte
)

func file_modules_proto_agent_proto_rawDescGZIP() []byte {
	file_modules_proto_agent_proto_rawDescOnce.Do(func() {
		file_modules_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_proto_agent_proto_rawDesc), len(file_modules_proto_agent_proto_rawDesc)))
	})
	return file_modules_proto_agent_proto_rawDescData
}

var file_modules_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_modules_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_modules_proto_agent_proto_goTypes = []any{
	(MessageType)(0),           // 0: agent.MessageType
	(DbType)(0),                // 1: agent.Db_type
	(Table)(0),                 // 2: agent.Table
	(ConnectStatus)(0),         // 3: agent.ConnectStatus
	(*AgentMessage)(nil),       // 4: agent.AgentMessage
	(*AgentPayload)(nil),       // 5: agent.AgentPayload
	(*Query)(nil),              // 6: agent.Query
	(*ACKReturn)(nil),          // 7: agent.ACKReturn
	(*ConnectedUser)(nil),      // 8: agent.ConnectedUser
	(*Erros)(nil),              // 9: agent.Erros
	(*Error)(nil),              // 10: agent.Error
	(*Produtos)(nil),           // 11: agent.Produtos
	(*Produto)(nil),            // 12: agent.Produto
	(*Clientes)(nil),           // 13: agent.Clientes
	(*Cliente)(nil),            // 14: agent.Cliente
	(*Categorias)(nil),         // 15: agent.Categorias
	(*Categoria)(nil),          // 16: agent.Categoria
	(*Vendedores)(nil),         // 17: agent.Vendedores
	(*Vendedor)(nil),           // 18: agent.Vendedor
	(*Vendas)(nil),             // 19: agent.Vendas
	(*Venda)(nil),              // 20: agent.Venda
	(*ProdutosVendas)(nil),     // 21: agent.Produtos_vendas
	(*DatasVencimento)(nil),    // 22: agent.Datas_vencimento
	(*Financeiros)(nil),        // 23: agent.Financeiros
	(*Financeiro)(nil),         // 24: agent.Financeiro
	(*InfosObranca)(nil),       // 25: agent.Infos_obranca
	(*structpb.ListValue)(nil), // 26: google.protobuf.ListValue
}
var file_modules_proto_agent_proto_depIdxs = []int32{
	0,  // 0: agent.AgentMessage.type:type_name -> agent.MessageType
	5,  // 1: agent.AgentMessage.payload:type_name -> agent.AgentPayload
	2,  // 2: agent.AgentMessage.table:type_name -> agent.Table
	11, // 3: agent.AgentPayload.produtos:type_name -> agent.Produtos
	19, // 4: agent.AgentPayload.vendas:type_name -> agent.Vendas
	13, // 5: agent.AgentPayload.clientes:type_name -> agent.Clientes
	15, // 6: agent.AgentPayload.categorias:type_name -> agent.Categorias
	17, // 7: agent.AgentPayload.vendedores:type_name -> agent.Vendedores
	23, // 8: agent.AgentPayload.financeiros:type_name -> agent.Financeiros
	26, // 9: agent.AgentPayload.generic_return:type_name -> google.protobuf.ListValue
	6,  // 10: agent.AgentPayload.query_request:type_name -> agent.Query
	9,  // 11: agent.AgentPayload.erros:type_name -> agent.Erros
	7,  // 12: agent.AgentPayload.ack_return:type_name -> agent.ACKReturn
	3,  // 13: agent.ACKReturn.status:type_name -> agent.ConnectStatus
	8,  // 14: agent.ACKReturn.connected_user:type_name -> agent.ConnectedUser
	1,  // 15: agent.ConnectedUser.db_type:type_name -> agent.Db_type
	10, // 16: agent.Erros.error:type_name -> agent.Error
	12, // 17: agent.Produtos.items:type_name -> agent.Produto
	14, // 18: agent.Clientes.items:type_name -> agent.Cliente
	16, // 19: agent.Categorias.items:type_name -> agent.Categoria
	18, // 20: agent.Vendedores.items:type_name -> agent.Vendedor
	20, // 21: agent.Vendas.items:type_name -> agent.Venda
	21, // 22: agent.Venda.produtos_venda:type_name -> agent.Produtos_vendas
	22, // 23: agent.Venda.datas_vencimento:type_name -> agent.Datas_vencimento
	24, // 24: agent.Financeiros.items:type_name -> agent.Financeiro
	25, // 25: agent.Financeiro.infos_cobranca:type_name -> agent.Infos_obranca
	4,  // 26: agent.AgentService.Connect:input_type -> agent.AgentMessage
	4,  // 27: agent.AgentService.Connect:output_type -> agent.AgentMessage
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_modules_proto_agent_proto_init() }
func file_modules_proto_agent_proto_init() {
	if File_modules_proto_agent_proto != nil {
		return
	}
	file_modules_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentPayload_Produtos)(nil),
		(*AgentPayload_Vendas)(nil),
		(*AgentPayload_Clientes)(nil),
		(*AgentPayload_Categorias)(nil),
		(*AgentPayload_Vendedores)(nil),
		(*AgentPayload_Financeiros)(nil),
		(*AgentPayload_GenericReturn)(nil),
		(*AgentPayload_QueryRequest)(nil),
		(*AgentPayload_Erros)(nil),
		(*AgentPayload_AckReturn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_proto_agent_proto_rawDesc), len(file_modules_proto_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_proto_agent_proto_goTypes,
		DependencyIndexes: file_modules_proto_agent_proto_depIdxs,
		EnumInfos:         file_modules_proto_agent_proto_enumTypes,
		MessageInfos:      file_modules_proto_agent_proto_msgTypes,
	}.Build()
	File_modules_proto_agent_proto = out.File
	file_modules_proto_agent_proto_goTypes = nil
	file_modules_proto_agent_proto_depIdxs = nil
}
